name: Nuget push (tag)

on: 
  push:
    tags:
    - 'v*'

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
    # We do not need to fetch tags, as we're already at a tagged build - it should be available automatically

    - name: Setup .NET
      uses: actions/setup-dotnet@d4c94342e560b34958eacfc5d055d21461ed1c5d # v5
      with:
        dotnet-version: 7.0.x

    - name: Pack
      run: dotnet pack -c Release -o Build

    - name: ls
      run: ls -alh Build/
    
    - name: Nuget push (github)
      run: dotnet nuget push --no-symbols --skip-duplicate -k ${{ secrets.GITHUB_TOKEN }} -s "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" Build/*.nupkg
      
    - name: Nuget push 
      run: dotnet nuget push --skip-duplicate -k ${{secrets.NUGET_APIKEY}} -s https://api.nuget.org/v3/index.json Build/*.nupkg
